### ISSUE TITLE
Yogi docs tries to pull gallery plugin from CDN

### ISSUE THREAD

**Issue by ymschaap** [yui/yogi#57] opened 2013-02-08 16:23 UTC
When creating the documentation for my gallery module I create an example page using the standard way to pull in a module:

``` js
YUI().use('gallery-module-name', function(Y)
```

But that leads to an error because YUI tries to pull the gallery module from:

> http://yui.yahooapis.com/combo?gallery-2012.11.09-01-41/build/gallery-plugin-name/gallery-module-name-min.js

Which is an 404, because the gallery module isn't pushed/live yet. Apparently I need to tell Yogi where my local gallery module is located.

To fix the example page, I set the Y config to pull any gallery modules locally:

``` js
gallery: {
    combine: false,
    base: "/build/",
    root: "/build/",
    patterns: {
        "gallery-": {},
        "gallerycss-": { type: "css" }
    }
}
```

But then I get another 404 (YOGI Not Found):

> http://127.0.0.1:5000/build/gallery-module-name/gallery-module-name-min.js

Given Yogi is used to create module files, I believe it shouldn't need extra code to load the 'local' version in the docs files, which is only confusing for an example page. 

Shifter builds the files fine.

(yogi version 0.0.67)

Update: I was able to get the local build not 404 by removing and installing yogi, not sure what caused it. The request to not need custom yui gallery code to pull the javascript from the local build still holds.

**Comment by tilomitra** [comment] 2013-03-19 15:02
Hey @davglass I'm running into this issue as well. Steps to reproduce:
1. `yogi create my-module --init`
2. Write my module, include unit tests, etc.
3. In my unit test, I have my config set to this: https://gist.github.com/tilomitra/5196806
4. `yogi test` or `yogi serve --istanbul` both fail to run through my tests. I believe the error for both of them is the same. There's a 404 because it can't find `gallery-widget-pointer.js`

`GET http://localhost:5001/build/gallery-widget-pointer/gallery-widget-pointer.js 404 (Not Found) yui-min.js:6
GET http://localhost:5001/build/gallery-widget-pointer/gallery-widget-pointer.js 404 (Not Found)`

Doing yogi test --debug shows that yogi is trying to fetch this module from the CDN with the latest gallery build tag, but I haven't pushed it out yet. Is there a way to get coverage through Istanbul when your gallery module isn't on the CDN?

**Comment by caridy** [comment] 2014-09-03 15:40
this is not longer relevant! closing!

**Closed as completed by caridy** 2014-09-03 15:40 UTC
